---
- name: Install Java on Debian/Ubuntu
  block:
    - name: Add Java repository (Ubuntu)
      apt_repository:
        repo: "ppa:openjdk-r/ppa"
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install OpenJDK on Debian/Ubuntu
      apt:
        name: "openjdk-{{ java_version }}-jdk"
        state: present
        update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Java on RedHat
  package:
    name: "java-{{ java_version }}-openjdk-devel"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Set JAVA_HOME for Debian/Ubuntu
  lineinfile:
    path: /etc/environment
    regexp: '^JAVA_HOME='
    line: "JAVA_HOME=/usr/lib/jvm/java-{{ java_version }}-openjdk-amd64"
    state: present
  when: ansible_os_family == 'Debian'

- name: Set JAVA_HOME for RedHat
  lineinfile:
    path: /etc/environment
    regexp: '^JAVA_HOME='
    line: "JAVA_HOME=/usr/lib/jvm/java-{{ java_version }}-openjdk"
    state: present
  when: ansible_os_family == 'RedHat'
