---
galaxy_info:
  author: your_name
  description: Ansible role to install and configure ELK Stack
  company: your_company
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - 8
        - 9
  galaxy_tags:
    - elk
    - elasticsearch
    - logstash
    - kibana
    - monitoring
    - logging

dependencies: []
