---
# Elasticsearch Configuration
elasticsearch_version: "8.11.0"
elasticsearch_http_port: 9200
elasticsearch_transport_port: 9300
elasticsearch_cluster_name: "elk-cluster"
elasticsearch_node_name: "node-1"
elasticsearch_heap_size: "1g"
elasticsearch_data_dir: "/var/lib/elasticsearch"
elasticsearch_log_dir: "/var/log/elasticsearch"

# Kibana Configuration
kibana_version: "8.11.0"
kibana_port: 5601
kibana_elasticsearch_hosts: ["http://localhost:9200"]
kibana_elasticsearch_username: "kibana_system"
kibana_elasticsearch_password: "changeme"  # Replace with secure value (e.g., via vault)

# Logstash Configuration
logstash_version: "8.11.0"
logstash_http_port: 9600
logstash_pipeline_workers: 2
logstash_heap_size: "1g"
logstash_data_dir: "/var/lib/logstash"
logstash_log_dir: "/var/log/logstash"

# Java configuration
java_version: "17"

# System configuration
elk_user: "elastic"
elk_group: "elastic"
elastic_security_enabled: true
elk_ssl_enabled: false
ssl_cert_path: "/etc/elasticsearch/certs"

# Network configuration
network_host: "0.0.0.0"
